### ISSUE TITLE
[Feature Request] Add "scripting" including controller inputs

### ISSUE THREAD

**Issue by whackawaldo** [davidgfnet/miniretro#1]
Thanks for building this, I think it's brilliant.

Something that might help automated testing even more would be to add support for controller inputs that can be scripted. For example, I'd like to write a test like this:
```yaml
test_some_game:
  core: somecore.so
  rom: somegame.bin
  script:
    sleep: 30s
    input: BUTTON_START
    sleep: 5s
    input: BUTTON_A
    screenshot: test_output.png
```
